In [31]:
import pandas as pd
import numpy as np

In [32]:
departments = pd.read_csv("Data/departments.csv")
diagnosis = pd.read_csv("Data/diagnosis.csv")
encounters = pd.read_csv("Data/encounters.csv")
patients = pd.read_csv("Data/patients.csv")
providers = pd.read_csv("Data/providers.csv")
social_determinants = pd.read_csv("Data/social_determinants.csv")
tigercensuscodes = pd.read_csv("Data/tigercensuscodes.csv")

/var/folders/r9/mhc5twwx0blgr6rw0wr28jmc0000gn/T/ipykernel_63424/2207771560.py:6: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  social_determinants = pd.read_csv("Data/social_determinants.csv")

In [33]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [34]:
departments.head()

,DepartmentKey,Address,City,County,DepartmentName,DepartmentSpecialty,DepartmentType,PostalCode,CensusTract
0,-3,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,NaN
1,-2,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,NaN
2,-1,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,NaN
3,1,1500 SW 10th ST,TOPEKA,*Unspecified,INITIAL DEPT,*Unspecified,*Unknown,66604,2.017700e+10
4,2,1979 Milky Way,VERONA,*Unspecified,EHS UM DEPT,*Unspecified,*Unknown,53593,5.502501e+10

In [35]:
diagnosis.head()

,DiagnosisKey,GroupName,GroupCode,DiagnosisName,DiagnosisValue
0,2.0,Typhoid and paratyphoid fevers,ICD-10-CM: A01,"Paratyphoid fever, unspecified( ICD-10-CM: A01...",A01.4
1,3.0,Respiratory tuberculosis,ICD-10-CM: A15,Primary respiratory tuberculosis( ICD-10-CM: A...,A15.7
2,7.0,Fracture at wrist and hand level,ICD-10-CM: S62,"Displaced fracture of pisiform, unspecified wr...",S62.163K
3,8.0,Fracture of rib,ICD-10-CM: S22,"Multiple fractures of ribs, right side, subseq...",S22.41XG
4,9.0,Fracture at wrist and hand level,ICD-10-CM: S62,Nondisplaced fracture of distal phalanx of lef...,S62.663G

In [36]:
encounters.head()

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,DischargeYear,DischargeMonth,DischargeDay,DischargeHour,DischargeMinute,EncounterKey,PatientDurableKey,Type,VisitType,VisitTypeDescription,ProviderDurableKey,AttendingProviderDurableKey,DischargeProviderDurableKey,DepartmentKey,PrimaryDiagnosisKey,IsEdVisit,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,2022.0,4.0,25.0,21.0,35.0,7848127,86333,Hospital Encounter,*Unspecified,*Unspecified,2982,2982,2982,27,910699,0,1,0,0,1,0
1,04/29/22,2022-04-29 18:18:00,2022.0,4.0,29.0,18.0,18.0,Clinic/Physician Referral,Elective,2022-04-29 18:20:00,2022.0,4.0,29.0,18.0,20.0,9333470,626973,Hospital Encounter,*Unspecified,*Unspecified,2979,2979,2979,27,-1,0,1,0,0,1,0
2,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,2022.0,1.0,12.0,11.0,43.0,29444575,236044,Hospital Encounter,*Unspecified,*Unspecified,6223,6223,7015,27,468738,0,1,0,1,0,0
3,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,2022.0,3.0,10.0,13.0,45.0,30915704,385246,Hospital Encounter,*Unspecified,*Unspecified,7973,7973,7973,27,468492,0,1,0,1,0,0
4,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,2022.0,3.0,16.0,16.0,0.0,33223911,353096,Hospital Encounter,*Unspecified,*Unspecified,6223,6223,2982,27,907210,0,1,0,0,1,0

In [37]:
patients.head()

,CensusBlockGroupFipsCode,DurableKey,FirstRace,MaritalStatus,MyChartStatus,OmbEthnicity,OmbRace,SexAssignedAtBirth,SexualOrientation,SmokingStatus,VitalStatus,PatientBirthYearBin
0,201770007002,5.0,White or Caucasian,Single,Activated,Not Hispanic or Latino,White,*Unspecified,*Unspecified,Never,Alive,1970.0
1,*Unspecified,8.0,White or Caucasian,*Unspecified,Inactivated,Unknown,White,*Unspecified,*Unspecified,*Unknown,Alive,1980.0
2,*Unspecified,9.0,"Hispanic, Latino, or Spanish",Married,*Unspecified,Unknown,Some Other Race,*Unspecified,*Unspecified,Never,Alive,1955.0
3,*Unspecified,11.0,"Hispanic, Latino, or Spanish",Unknown,*Unspecified,Hispanic or Latino,Some Other Race,*Unspecified,*Unspecified,Never,Alive,1970.0
4,*Unspecified,12.0,Black or African American,Single,*Unspecified,Not Hispanic or Latino,Black or African American,*Unspecified,*Unspecified,Never,Alive,1980.0

In [38]:
providers.head()

,DurableKey,ClinicianTitle,OfficeAddress,OfficeCity,OfficePostalCode,PrimaryDepartment,PrimarySpecialty,Type
0,-3.0,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted
1,-2.0,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable
2,-1.0,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified
3,1.0,*Unspecified,NaN,NaN,NaN,*Unspecified,NaN,Technician
4,2.0,MODEL USER,NaN,NaN,NaN,*Unspecified,Emergency Medicine,Physician

In [58]:
social_determinants.sample(10)

,DisplayName,AnswerText,EncounterKey,PatientDurableKey,Domain
2458772,Do you belong to any clubs or organizations su...,No,152003015.0,761507.0,social connections
3702415,"Within the last year, have you been humiliated...",No,136568691.0,7189224.0,intimate partner violance
3939337,"Within the past 12 months, you worried that yo...",Never true,139649393.0,82148.0,Food insecurity
2979989,"In the past 12 months has the electric, gas, o...",No,144703799.0,10862752.0,Financial Resource Strain
3833761,"Within the past 12 months, the food you bought...",Never true,134756050.0,6868756.0,Food insecurity
2043972,*Unspecified,Never,153028213.0,7117326.0,NaN
1382593,*Unspecified,Every Day,134688472.0,6785079.0,NaN
3106831,"In the past 12 months, has lack of transportat...",No,142919121.0,7037676.0,Transportation Needs
3174681,"In the past 12 months, has lack of transportat...",No,143980007.0,5712488.0,Transportation Needs
1677992,*Unspecified,Never,145860567.0,10906699.0,NaN

In [40]:
tigercensuscodes.head()

          GEOID  PopulationValue    CENTLAT    CENTLON
0  200019526001           1791.0  37.873751 -95.203664
1  200019527001           1052.0  37.987188 -95.380907
2  200019527002            957.0  37.907415 -95.344626
3  200019528001           1179.0  37.942439 -95.420724
4  200019528002           1541.0  37.947521 -95.381379

In [50]:
import duckdb
AllData = duckdb.sql("""
       SELECT *
       FROM encounters e
       LEFT JOIN departments d
       ON e.DepartmentKey = d.DepartmentKey
       LEFT JOIN diagnosis di
       ON e.PrimaryDiagnosisKey = di.DiagnosisKey
       LEFT JOIN patients p
       ON e.PatientDurableKey = p.DurableKey
       LEFT JOIN providers pr
       ON e.PatientDurableKey = pr.DurableKey
       LEFT JOIN social_determinants s
       ON e.EncounterKey = s.EncounterKey
       """)


EncounterLevel = duckdb.sql("""
WITH encounter_level AS (
   SELECT DISTINCT
       EncounterKey,
       PatientDurableKey,
       COALESCE(
           TRY_STRPTIME(Date, '%m/%d/%y'),
           TRY_STRPTIME(Date, '%m/%d/%Y')
       ) AS EncounterDate,

       DepartmentKey,
       DepartmentName,

       DiagnosisKey,
       DiagnosisName,
       DiagnosisValue,
       GroupCode,
       GroupName,

       IsEDVisit,
       IsHospitalAdmission,
       IsHospitalOutpatientVisit,
       IsInpatientAdmission,
       IsObservation,
       IsOutpatientFaceToFaceVisit,

       Type,
       VisitType,
       VisitTypeDescription,

       CensusTract,
       FirstRace,
       MaritalStatus,
       MyChartStatus,
       OmbEthnicity,
       OmbRace,
       PatientBirthYearBin,
       SexAssignedAtBirth,
       SexualOrientation,
       SmokingStatus,
       VitalStatus

   FROM AllData
)
SELECT *
FROM encounter_level
""")


# --------------------------------------------
# MAIN JOURNEY TABLE
# --------------------------------------------
JourneyTable = duckdb.sql("""
WITH encounter_level AS (
   SELECT *
   FROM EncounterLevel
),


data_end AS (
   SELECT MAX(EncounterDate) AS DataEndDate
   FROM encounter_level
),


diabetes_outpatient AS (
   SELECT
       *,
       ROW_NUMBER() OVER (
           PARTITION BY PatientDurableKey
           ORDER BY EncounterDate, EncounterKey
       ) AS rn
   FROM encounter_level
   WHERE GroupName = 'Type 2 diabetes mellitus'
     AND IsOutpatientFaceToFaceVisit = 1
),


index_visits AS (
   SELECT
       PatientDurableKey,
       EncounterKey AS IndexEncounterKey,
       EncounterDate AS IndexOutpatientDate,


       DepartmentKey AS IndexDepartmentKey,
       DepartmentName AS IndexDepartmentName,


       DiagnosisKey AS IndexDiagnosisKey,
       DiagnosisName AS IndexDiagnosisName,
       DiagnosisValue AS IndexDiagnosisValue,
       GroupCode AS IndexGroupCode,
       GroupName AS IndexGroupName,


       Type AS IndexEncounterType,
       VisitType AS IndexVisitType,
       VisitTypeDescription AS IndexVisitTypeDescription,


       CensusTract,
       FirstRace,
       MaritalStatus,
       MyChartStatus,
       OmbEthnicity,
       OmbRace,
       PatientBirthYearBin,
       SexAssignedAtBirth,
       SexualOrientation,
       SmokingStatus,
       VitalStatus
   FROM diabetes_outpatient
   WHERE rn = 1
),


next_diabetes_outpatient AS (
   SELECT
       i.PatientDurableKey,
       MIN(e.EncounterDate) AS SecondOutpatientDate
   FROM index_visits i
   JOIN encounter_level e
     ON e.PatientDurableKey = i.PatientDurableKey
    AND e.GroupName = 'Type 2 diabetes mellitus'
    AND e.IsOutpatientFaceToFaceVisit = 1
    AND (
           e.EncounterDate > i.IndexOutpatientDate
           OR (e.EncounterDate = i.IndexOutpatientDate AND e.EncounterKey <> i.IndexEncounterKey)
        )
   GROUP BY i.PatientDurableKey
),


first_ed_after_index AS (
   SELECT
       i.PatientDurableKey,
       MIN(e.EncounterDate) AS FirstEDDate
   FROM index_visits i
   JOIN encounter_level e
     ON e.PatientDurableKey = i.PatientDurableKey
    AND e.IsEDVisit = 1
    AND (
           e.EncounterDate > i.IndexOutpatientDate
           OR (e.EncounterDate = i.IndexOutpatientDate AND e.EncounterKey <> i.IndexEncounterKey)
        )
   GROUP BY i.PatientDurableKey
),


first_inpatient_after_index AS (
   SELECT
       i.PatientDurableKey,
       MIN(e.EncounterDate) AS FirstInpatientDate
   FROM index_visits i
   JOIN encounter_level e
     ON e.PatientDurableKey = i.PatientDurableKey
    AND e.IsInpatientAdmission = 1
    AND (
           e.EncounterDate > i.IndexOutpatientDate
           OR (e.EncounterDate = i.IndexOutpatientDate AND e.EncounterKey <> i.IndexEncounterKey)
        )
   GROUP BY i.PatientDurableKey
)


SELECT
   i.*,
   d.DataEndDate,
   DATEDIFF('day', i.IndexOutpatientDate, d.DataEndDate) AS DaysObservedAfterIndex,


   CASE
       WHEN DATEDIFF('day', i.IndexOutpatientDate, d.DataEndDate) >= 180 THEN 1
       ELSE 0
   END AS CanObserve180Days,


   o.SecondOutpatientDate,
   CASE
       WHEN o.SecondOutpatientDate IS NOT NULL
       THEN DATEDIFF('day', i.IndexOutpatientDate, o.SecondOutpatientDate)
       ELSE NULL
   END AS DaysToSecondOutpatient,


   ed.FirstEDDate,
   CASE
       WHEN ed.FirstEDDate IS NOT NULL
       THEN DATEDIFF('day', i.IndexOutpatientDate, ed.FirstEDDate)
       ELSE NULL
   END AS DaysToFirstED,


   ip.FirstInpatientDate,
   CASE
       WHEN ip.FirstInpatientDate IS NOT NULL
       THEN DATEDIFF('day', i.IndexOutpatientDate, ip.FirstInpatientDate)
       ELSE NULL
   END AS DaysToFirstInpatient,


   CASE
       WHEN ed.FirstEDDate IS NOT NULL
            AND (o.SecondOutpatientDate IS NULL OR ed.FirstEDDate < o.SecondOutpatientDate)
       THEN 1
       ELSE 0
   END AS EDBeforeFollowup,


   CASE
       WHEN ip.FirstInpatientDate IS NOT NULL
            AND (o.SecondOutpatientDate IS NULL OR ip.FirstInpatientDate < o.SecondOutpatientDate)
       THEN 1
       ELSE 0
   END AS InpatientBeforeFollowup,


   CASE
       WHEN DATEDIFF('day', i.IndexOutpatientDate, d.DataEndDate) < 180 THEN NULL
       WHEN o.SecondOutpatientDate IS NULL THEN 1
       WHEN DATEDIFF('day', i.IndexOutpatientDate, o.SecondOutpatientDate) > 180 THEN 1
       ELSE 0
   END AS Broken180_NoTimelyFollowup,


   CASE
       WHEN DATEDIFF('day', i.IndexOutpatientDate, d.DataEndDate) < 180 THEN NULL
       WHEN (
               ed.FirstEDDate IS NOT NULL
               AND DATEDIFF('day', i.IndexOutpatientDate, ed.FirstEDDate) <= 90
               AND (o.SecondOutpatientDate IS NULL OR ed.FirstEDDate < o.SecondOutpatientDate)
            )
            OR (
               ip.FirstInpatientDate IS NOT NULL
               AND DATEDIFF('day', i.IndexOutpatientDate, ip.FirstInpatientDate) <= 90
               AND (o.SecondOutpatientDate IS NULL OR ip.FirstInpatientDate < o.SecondOutpatientDate)
            )
            OR o.SecondOutpatientDate IS NULL
            OR DATEDIFF('day', i.IndexOutpatientDate, o.SecondOutpatientDate) > 180
       THEN 1
       ELSE 0
   END AS BrokenComposite_180_90


FROM index_visits i
CROSS JOIN data_end d
LEFT JOIN next_diabetes_outpatient o
   ON i.PatientDurableKey = o.PatientDurableKey
LEFT JOIN first_ed_after_index ed
   ON i.PatientDurableKey = ed.PatientDurableKey
LEFT JOIN first_inpatient_after_index ip
   ON i.PatientDurableKey = ip.PatientDurableKey
ORDER BY i.IndexOutpatientDate
""")

In [51]:
journey_df = JourneyTable.df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [53]:
journey_df.head(10)

,PatientDurableKey,IndexEncounterKey,IndexOutpatientDate,IndexDepartmentKey,IndexDepartmentName,IndexDiagnosisKey,IndexDiagnosisName,IndexDiagnosisValue,IndexGroupCode,IndexGroupName,IndexEncounterType,IndexVisitType,IndexVisitTypeDescription,CensusTract,FirstRace,MaritalStatus,MyChartStatus,OmbEthnicity,OmbRace,PatientBirthYearBin,SexAssignedAtBirth,SexualOrientation,SmokingStatus,VitalStatus,DataEndDate,DaysObservedAfterIndex,CanObserve180Days,SecondOutpatientDate,DaysToSecondOutpatient,FirstEDDate,DaysToFirstED,FirstInpatientDate,DaysToFirstInpatient,EDBeforeFollowup,InpatientBeforeFollowup,Broken180_NoTimelyFollowup,BrokenComposite_180_90
0,6746880,99160928,2022-01-03,299,6TH FRAZIER ENDOCRINOLOGY,405570.0,Type 2 diabetes mellitus with hyperglycemia (H...,E11.65,ICD-10-CM: E11,Type 2 diabetes mellitus,Follow-Up,FOLLOW UP,Clinic Visits- In Person,2.017700e+10,White or Caucasian,Single,Activated,Not Hispanic or Latino,White,1970.0,Female,Straight,Never,Alive,2025-12-31,1458,1,2022-01-03,0,2023-09-01,606,NaT,<NA>,0,0,0,0
1,529566,98318395,2022-01-03,834,CORPORATE VIEW CLINIC,406269.0,Type 2 diabetes mellitus without complications...,E11.9,ICD-10-CM: E11,Type 2 diabetes mellitus,Office Visit,FOLLOW UP,Clinic Visits- In Person,NaN,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1970.0,*Unspecified,*Unspecified,Never,Alive,2025-12-31,1458,1,2023-11-29,695,2025-07-13,1287,NaT,<NA>,0,0,1,1
2,6898291,90617718,2022-01-03,299,6TH FRAZIER ENDOCRINOLOGY,405570.0,Type 2 diabetes mellitus with hyperglycemia (H...,E11.65,ICD-10-CM: E11,Type 2 diabetes mellitus,Follow-Up,FOLLOW UP,Clinic Visits- In Person,2.017700e+10,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1975.0,Female,Straight,Never,Alive,2025-12-31,1458,1,2022-06-09,157,2025-10-05,1371,2025-10-05,1371,0,0,0,0
3,8940412,96003508,2022-01-03,478,NORTH FIELDING CLINIC,406269.0,Type 2 diabetes mellitus without complications...,E11.9,ICD-10-CM: E11,Type 2 diabetes mellitus,Office Visit,FOLLOW UP,Clinic Visits- In Person,2.017700e+10,White or Caucasian,Divorced,Activated,Not Hispanic or Latino,White,1950.0,Male,Straight,Never,Alive,2025-12-31,1458,1,2023-12-14,710,2025-05-25,1238,2025-05-25,1238,0,0,1,1
4,7416578,99105649,2022-01-03,299,6TH FRAZIER ENDOCRINOLOGY,405912.0,Type 2 diabetes mellitus with diabetic polyneu...,E11.42,ICD-10-CM: E11,Type 2 diabetes mellitus,Follow-Up,FOLLOW UP,Clinic Visits- In Person,2.017700e+10,None,None,None,None,None,NaN,None,None,None,None,2025-12-31,1458,1,2022-04-11,98,2022-09-19,259,2022-12-03,334,0,0,0,0
5,6208286,99013829,2022-01-03,834,CORPORATE VIEW CLINIC,406269.0,Type 2 diabetes mellitus without complications...,E11.9,ICD-10-CM: E11,Type 2 diabetes mellitus,Office Visit,FOLLOW UP,Clinic Visits- In Person,NaN,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1960.0,*Unspecified,*Unspecified,Former,Alive,2025-12-31,1458,1,2022-09-20,260,NaT,<NA>,NaT,<NA>,0,0,1,1
6,2844240,99159282,2022-01-03,278,EMPORIA INTERNAL MED,406379.0,Type 2 diabetes mellitus without complications...,E11.9,ICD-10-CM: E11,Type 2 diabetes mellitus,Office Visit,FOLLOW UP,Clinic Visits- In Person,2.011100e+10,None,None,None,None,None,NaN,None,None,None,None,2025-12-31,1458,1,2022-03-29,85,NaT,<NA>,NaT,<NA>,0,0,0,0
7,5515260,99336830,2022-01-03,278,EMPORIA INTERNAL MED,405806.0,Type 2 diabetes mellitus with diabetic polyneu...,E11.42,ICD-10-CM: E11,Type 2 diabetes mellitus,Office Visit,FOLLOW UP,Clinic Visits- In Person,2.011100e+10,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1950.0,*Unspecified,*Unspecified,Never,Alive,2025-12-31,1458,1,2022-07-08,186,NaT,<NA>,NaT,<NA>,0,0,1,1
8,5249129,99689683,2022-01-03,299,6TH FRAZIER ENDOCRINOLOGY,30252.0,Type 2 diabetes mellitus with diabetic polyneu...,E11.42,ICD-10-CM: E11,Type 2 diabetes mellitus,Follow-Up,FOLLOW UP,Clinic Visits- In Person,2.017700e+10,White or Caucasian,Divorced,Activated,Not Hispanic or Latino,White,1960.0,Female,Straight,Former,Alive,2025-12-31,1458,1,2022-01-05,2,2023-08-30,604,2022-10-27,297,0,0,0,0
9,2512136,96497317,2022-01-03,834,CORPORATE VIEW CLINIC,1571960.0,Type 2 diabetes mellitus with diabetic chronic...,E11.22,ICD-10-CM: E11,Type 2 diabetes mellitus,Office Visit,FOLLOW UP,Clinic Visits- In Person,NaN,White or Caucasian,Married,Pending Activation,Not Hispanic or Latino,White,1945.0,*Unspecified,*Unspecified,Never,Alive,2025-12-31,1458,1,NaT,<NA>,NaT,<NA>,NaT,<NA>,0,0,1,1

In [54]:
journey_df.columns

Index(['PatientDurableKey', 'IndexEncounterKey', 'IndexOutpatientDate',
       'IndexDepartmentKey', 'IndexDepartmentName', 'IndexDiagnosisKey',
       'IndexDiagnosisName', 'IndexDiagnosisValue', 'IndexGroupCode',
       'IndexGroupName', 'IndexEncounterType', 'IndexVisitType',
       'IndexVisitTypeDescription', 'CensusTract', 'FirstRace',
       'MaritalStatus', 'MyChartStatus', 'OmbEthnicity', 'OmbRace',
       'PatientBirthYearBin', 'SexAssignedAtBirth', 'SexualOrientation',
       'SmokingStatus', 'VitalStatus', 'DataEndDate', 'DaysObservedAfterIndex',
       'CanObserve180Days', 'SecondOutpatientDate', 'DaysToSecondOutpatient',
       'FirstEDDate', 'DaysToFirstED', 'FirstInpatientDate',
       'DaysToFirstInpatient', 'EDBeforeFollowup', 'InpatientBeforeFollowup',
       'Broken180_NoTimelyFollowup', 'BrokenComposite_180_90'],
      dtype='object')

In [134]:
data2  = pd.read_csv("Data/output2.csv")

In [ ]:
data2["distance"]

Index(['PatientDurableKey', 'IndexEncounterKey', 'FirstOutpatientDate',
       'IndexYear', 'IndexMonth', 'IndexDayOfWeek', 'IndexDepartmentKey',
       'IndexDepartmentName', 'IndexDepartmentType',
       'IndexDepartmentSpecialty', 'IndexDepartmentCity',
       'IndexDepartmentCounty', 'IndexDepartmentPostalCode',
       'IndexDepartmentCensusTract', 'IndexDiagnosisName',
       'IndexDiagnosisValue', 'IndexGroupCode', 'IndexGroupName',
       'IndexAdmissionSource', 'IndexAdmissionType', 'IndexVisitType',
       'IndexVisitTypeDescription', 'CensusBlockGroupFipsCode', 'FirstRace',
       'MaritalStatus', 'MyChartStatus', 'OmbEthnicity', 'OmbRace',
       'PatientBirthYearBin', 'SexAssignedAtBirth', 'SexualOrientation',
       'SmokingStatus', 'VitalStatus', 'ClinicianTitle', 'PrimaryDepartment',
       'PrimarySpecialty', 'OfficeCity', 'OfficePostalCode', 'DataEndDate',
       'DaysObservedAfterIndex', 'SecondOutpatientDate',
       'DaysBetweenFirstSecond', 'FirstEDDate', 'DaysUntilED',
       'FirstInpatientDate', 'DaysUntilInpatient', 'isBroken', 'isAcute',
       'DaysSincePrevEncounter', 'DaysSincePrevDiabetesEncounter',
       'PriorEncounters180', 'PriorOutpatient180', 'PriorED180',
       'PriorInpatient180', 'PriorDiabetes180', 'PriorDistinctDepartments180',
       'PriorEncounters365', 'PriorED365', 'PriorInpatient365',
       'PriorDiabetes365', 'HasAnySDOHAtIndex'],
      dtype='object')

In [ ]:
drop_cols = [
    "PatientDurableKey",
    "IndexEncounterKey",
    "FirstOutpatientDate",
    "IndexDiagnosisName",
    "IndexDiagnosisValue",
    "IndexGroupCode",
    "IndexGroupName",
    "DataEndDate",
    "DaysObservedAfterIndex",
    "SecondOutpatientDate",
    "DaysBetweenFirstSecond",
    "FirstEDDate",
    "DaysUntilED",
    "FirstInpatientDate",
    "DaysUntilInpatient",
    "isAcute",
    "DaysSincePrevDiabetesEncounter",
    "DaysSincePrevEncounter",
    "PriorEncounters180",
    "PriorOutpatient180",
    "PriorED180",
    "PriorInpatient180",
    "PriorDiabetes180",
    "PriorDistinctDepartments180",
    "PriorEncounters365",
    "PriorED365",
    "PriorInpatient365",
    "PriorDiabetes365",
    "HasAnySDOHAtIndex"
]

model_df = data2.drop(columns=drop_cols)

In [99]:
model_df.shape

(20331, 43)

In [100]:
print(model_df.isna().sum().sort_values(ascending=False).to_string())

IndexDepartmentCensusTract     1916
FirstRace                      1426
PatientBirthYearBin            1046
VitalStatus                    1045
SmokingStatus                  1045
SexualOrientation              1045
SexAssignedAtBirth             1045
OmbRace                        1045
OmbEthnicity                   1045
MyChartStatus                  1045
MaritalStatus                  1045
CensusBlockGroupFipsCode       1045
PrimarySpecialty                 28
OfficePostalCode                  3
OfficeCity                        3
IndexAdmissionType                1
IndexAdmissionSource              1
PriorOutpatient180                0
PriorED180                        0
PriorInpatient180                 0
PriorDiabetes180                  0
isBroken                          0
PriorDistinctDepartments180       0
PriorEncounters365                0
PriorED365                        0
PriorInpatient365                 0
PriorDiabetes365                  0
PriorEncounters180                0
IndexYear                         0
PrimaryDepartment                 0
ClinicianTitle                    0
IndexMonth                        0
IndexVisitTypeDescription         0
IndexVisitType                    0
IndexDepartmentPostalCode         0
IndexDepartmentCounty             0
IndexDepartmentCity               0
IndexDepartmentSpecialty          0
IndexDepartmentType               0
IndexDepartmentName               0
IndexDepartmentKey                0
IndexDayOfWeek                    0
HasAnySDOHAtIndex                 0

In [101]:
model_df = model_df.drop(columns=["IndexDepartmentCensusTract", "CensusBlockGroupFipsCode"])

In [102]:
print(model_df.isna().sum().sort_values(ascending=False).to_string())

FirstRace                      1426
PatientBirthYearBin            1046
SexAssignedAtBirth             1045
VitalStatus                    1045
SmokingStatus                  1045
SexualOrientation              1045
OmbRace                        1045
OmbEthnicity                   1045
MyChartStatus                  1045
MaritalStatus                  1045
PrimarySpecialty                 28
OfficePostalCode                  3
OfficeCity                        3
IndexAdmissionType                1
IndexAdmissionSource              1
PriorOutpatient180                0
PriorED180                        0
PriorInpatient180                 0
PriorDiabetes180                  0
PriorDistinctDepartments180       0
isBroken                          0
PriorEncounters365                0
PriorED365                        0
PriorInpatient365                 0
PriorDiabetes365                  0
PriorEncounters180                0
IndexYear                         0
PrimaryDepartment                 0
ClinicianTitle                    0
IndexMonth                        0
IndexVisitTypeDescription         0
IndexVisitType                    0
IndexDepartmentPostalCode         0
IndexDepartmentCounty             0
IndexDepartmentCity               0
IndexDepartmentSpecialty          0
IndexDepartmentType               0
IndexDepartmentName               0
IndexDepartmentKey                0
IndexDayOfWeek                    0
HasAnySDOHAtIndex                 0

In [103]:
model_df_complete = model_df.dropna()

In [104]:
model_df_complete.shape

(18876, 41)

In [105]:
model_df["isBroken"].value_counts(normalize=True, dropna=False)

isBroken
1    0.535586
0    0.464414
Name: proportion, dtype: float64

In [122]:
missing_tokens = ["*Unknown", "Unknown", "None", "", "NaN", "*Not Applicable", "*Unspecified"]

model_clean = model_df_complete.replace(missing_tokens, "Missing")

In [123]:
model_clean.sample(10)

,IndexYear,IndexMonth,IndexDayOfWeek,IndexDepartmentKey,IndexDepartmentName,IndexDepartmentType,IndexDepartmentSpecialty,IndexDepartmentCity,IndexDepartmentCounty,IndexDepartmentPostalCode,IndexAdmissionSource,IndexAdmissionType,IndexVisitType,IndexVisitTypeDescription,FirstRace,MaritalStatus,MyChartStatus,OmbEthnicity,OmbRace,PatientBirthYearBin,SexAssignedAtBirth,SexualOrientation,SmokingStatus,VitalStatus,ClinicianTitle,PrimaryDepartment,PrimarySpecialty,OfficeCity,OfficePostalCode,isBroken,PriorEncounters180,PriorOutpatient180,PriorED180,PriorInpatient180,PriorDiabetes180,PriorDistinctDepartments180,PriorEncounters365,PriorED365,PriorInpatient365,PriorDiabetes365,HasAnySDOHAtIndex
7070,2022,5,4,338,823 SURGERY OPHTHALMOLOGY,Missing,Ophthalmology,Topeka,SHAWNEE,66606,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Divorced,Activated,Not Hispanic or Latino,White,1960.0,Male,Straight,Former,Alive,Missing,Missing,Missing,Missing,Missing,1,3,3,0,0,0,1,3,0,0,0,0
8642,2022,7,1,278,EMPORIA INTERNAL MED,Missing,Internal Medicine,Emporia,LYON,66801,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Widowed,Activated,Not Hispanic or Latino,White,1955.0,Female,Straight,Never,Alive,Missing,Missing,Missing,Missing,Missing,0,11,6,0,0,1,3,14,0,0,1,0
12406,2023,3,3,278,EMPORIA INTERNAL MED,Missing,Internal Medicine,Emporia,LYON,66801,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Single,Activated,Not Hispanic or Latino,White,1965.0,Missing,Missing,Never,Alive,Missing,Missing,Missing,Missing,Missing,0,12,11,0,1,1,5,12,0,1,1,0
615,2022,1,2,299,6TH FRAZIER ENDOCRINOLOGY,Missing,Endocrinology,Topeka,SHAWNEE,66606,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,Black or African American,Married,Pending Activation,Not Hispanic or Latino,Black or African American,1935.0,Missing,Missing,Former,Alive,Missing,Missing,Missing,Missing,Missing,0,0,0,0,0,0,0,0,0,0,0,0
433,2022,1,5,299,6TH FRAZIER ENDOCRINOLOGY,Missing,Endocrinology,Topeka,SHAWNEE,66606,Missing,Missing,FOLLOW UP EPIC VIDEO VISIT,Clinic Visits- Virtual,White or Caucasian,Single,Activated,Not Hispanic or Latino,White,1985.0,Male,Straight,Former,Alive,Missing,Missing,Missing,Missing,Missing,0,1,0,1,0,0,1,1,1,0,0,0
5895,2022,4,4,299,6TH FRAZIER ENDOCRINOLOGY,Missing,Endocrinology,Topeka,SHAWNEE,66606,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Divorced,Activated,Not Hispanic or Latino,White,1955.0,Female,Missing,Former,Alive,Missing,Missing,Missing,Missing,Missing,1,2,0,0,0,1,2,2,0,0,1,0
8051,2022,6,4,418,WAMEGO CLINIC,Missing,Family Medicine,Wamego,POTTAWATOMIE,66547,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Widowed,Patient Declined,Not Hispanic or Latino,White,1950.0,Missing,Missing,Never,Alive,Missing,Missing,Missing,Missing,Missing,1,10,5,0,0,0,2,10,0,0,0,0
18779,2024,11,5,299,6TH FRAZIER ENDOCRINOLOGY,Missing,Endocrinology,Topeka,SHAWNEE,66606,Missing,Missing,CONSULT,Clinic Visits- In person,"Hispanic, Latino, or Spanish",Missing,Activated,Hispanic or Latino,Some Other Race,1950.0,Missing,Missing,Never,Alive,Missing,Missing,Missing,Missing,Missing,0,23,21,2,0,0,9,25,2,0,0,0
15179,2023,10,1,349,901 INTERNAL MED,Missing,Internal Medicine,Topeka,SHAWNEE,66606,Missing,Missing,OFFICE VISIT,Clinic Visit- In Person,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1980.0,Female,Straight,Every Day,Alive,Missing,Missing,Missing,Missing,Missing,0,36,19,0,1,0,12,41,0,1,0,0
6580,2022,5,1,358,901 FAMILY PRACTICE,Missing,Family Medicine,Topeka,SHAWNEE,66606,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1975.0,Female,Straight,Never,Alive,Missing,Missing,Missing,Missing,Missing,1,1,0,0,0,0,1,1,0,0,0,0

In [ ]:
#model_clean.to_csv("cleaned_data", index = False)