In [3]:
import pandas as pd
import numpy as np

In [4]:
departments = pd.read_csv("Data/departments.csv")
diagnosis = pd.read_csv("Data/diagnosis.csv")
encounters = pd.read_csv("Data/encounters.csv")
patients = pd.read_csv("Data/patients.csv")
providers = pd.read_csv("Data/providers.csv")
social_determinants = pd.read_csv("Data/social_determinants.csv")
tigercensuscodes = pd.read_csv("Data/tigercensuscodes.csv")

/var/folders/r9/mhc5twwx0blgr6rw0wr28jmc0000gn/T/ipykernel_63424/2207771560.py:6: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  social_determinants = pd.read_csv("Data/social_determinants.csv")

In [14]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [16]:
departments.head()

,DepartmentKey,Address,City,County,DepartmentName,DepartmentSpecialty,DepartmentType,PostalCode,CensusTract
0,-3,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,NaN
1,-2,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,NaN
2,-1,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,NaN
3,1,1500 SW 10th ST,TOPEKA,*Unspecified,INITIAL DEPT,*Unspecified,*Unknown,66604,2.017700e+10
4,2,1979 Milky Way,VERONA,*Unspecified,EHS UM DEPT,*Unspecified,*Unknown,53593,5.502501e+10

In [17]:
diagnosis.head()

,DiagnosisKey,GroupName,GroupCode,DiagnosisName,DiagnosisValue
0,2.0,Typhoid and paratyphoid fevers,ICD-10-CM: A01,"Paratyphoid fever, unspecified( ICD-10-CM: A01...",A01.4
1,3.0,Respiratory tuberculosis,ICD-10-CM: A15,Primary respiratory tuberculosis( ICD-10-CM: A...,A15.7
2,7.0,Fracture at wrist and hand level,ICD-10-CM: S62,"Displaced fracture of pisiform, unspecified wr...",S62.163K
3,8.0,Fracture of rib,ICD-10-CM: S22,"Multiple fractures of ribs, right side, subseq...",S22.41XG
4,9.0,Fracture at wrist and hand level,ICD-10-CM: S62,Nondisplaced fracture of distal phalanx of lef...,S62.663G

In [18]:
encounters.head()

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,DischargeYear,DischargeMonth,DischargeDay,DischargeHour,DischargeMinute,EncounterKey,PatientDurableKey,Type,VisitType,VisitTypeDescription,ProviderDurableKey,AttendingProviderDurableKey,DischargeProviderDurableKey,DepartmentKey,PrimaryDiagnosisKey,IsEdVisit,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,2022.0,4.0,25.0,21.0,35.0,7848127,86333,Hospital Encounter,*Unspecified,*Unspecified,2982,2982,2982,27,910699,0,1,0,0,1,0
1,04/29/22,2022-04-29 18:18:00,2022.0,4.0,29.0,18.0,18.0,Clinic/Physician Referral,Elective,2022-04-29 18:20:00,2022.0,4.0,29.0,18.0,20.0,9333470,626973,Hospital Encounter,*Unspecified,*Unspecified,2979,2979,2979,27,-1,0,1,0,0,1,0
2,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,2022.0,1.0,12.0,11.0,43.0,29444575,236044,Hospital Encounter,*Unspecified,*Unspecified,6223,6223,7015,27,468738,0,1,0,1,0,0
3,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,2022.0,3.0,10.0,13.0,45.0,30915704,385246,Hospital Encounter,*Unspecified,*Unspecified,7973,7973,7973,27,468492,0,1,0,1,0,0
4,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,2022.0,3.0,16.0,16.0,0.0,33223911,353096,Hospital Encounter,*Unspecified,*Unspecified,6223,6223,2982,27,907210,0,1,0,0,1,0

In [ ]:
patients.head()

,CensusBlockGroupFipsCode,DurableKey,FirstRace,MaritalStatus,MyChartStatus,OmbEthnicity,OmbRace,SexAssignedAtBirth,SexualOrientation,SmokingStatus,VitalStatus,PatientBirthYearBin
0,201770007002,5.0,White or Caucasian,Single,Activated,Not Hispanic or Latino,White,*Unspecified,*Unspecified,Never,Alive,1970.0
1,*Unspecified,8.0,White or Caucasian,*Unspecified,Inactivated,Unknown,White,*Unspecified,*Unspecified,*Unknown,Alive,1980.0
2,*Unspecified,9.0,"Hispanic, Latino, or Spanish",Married,*Unspecified,Unknown,Some Other Race,*Unspecified,*Unspecified,Never,Alive,1955.0
3,*Unspecified,11.0,"Hispanic, Latino, or Spanish",Unknown,*Unspecified,Hispanic or Latino,Some Other Race,*Unspecified,*Unspecified,Never,Alive,1970.0
4,*Unspecified,12.0,Black or African American,Single,*Unspecified,Not Hispanic or Latino,Black or African American,*Unspecified,*Unspecified,Never,Alive,1980.0
5,*Unspecified,14.0,NaN,*Unspecified,*Unspecified,Unknown,Unknown,*Unspecified,*Unspecified,*Unknown,Alive,1995.0
6,201770030011,15.0,White or Caucasian,Single,Activated,Not Hispanic or Latino,White,*Unspecified,*Unspecified,Every Day,Alive,1985.0
7,200850826001,17.0,White or Caucasian,Married,Activated,Asked but No Answer,White,*Unspecified,*Unspecified,Never,Alive,1960.0
8,201770016032,19.0,White or Caucasian,Single,Pending Activation,Unknown,White,*Unspecified,*Unspecified,Never Assessed,Alive,2000.0
9,*Unspecified,21.0,White or Caucasian,*Unspecified,Inactivated,Unknown,White,*Unspecified,*Unspecified,*Unknown,Alive,1910.0

In [11]:
providers.head()

,DurableKey,ClinicianTitle,OfficeAddress,OfficeCity,OfficePostalCode,PrimaryDepartment,PrimarySpecialty,Type
0,-3.0,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted,*Deleted
1,-2.0,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable,*Not Applicable
2,-1.0,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified,*Unspecified
3,1.0,*Unspecified,NaN,NaN,NaN,*Unspecified,NaN,Technician
4,2.0,MODEL USER,NaN,NaN,NaN,*Unspecified,Emergency Medicine,Physician

In [20]:
social_determinants.head()

    DisplayName AnswerText  EncounterKey  PatientDurableKey Domain
0  *Unspecified    Unknown   147506236.0                5.0    NaN
1  *Unspecified      Never   154008498.0          6094715.0    NaN
2  *Unspecified      Never   152425953.0          6094715.0    NaN
3  *Unspecified       Past   153702939.0                5.0    NaN
4  *Unspecified       Past   152713763.0                5.0    NaN

In [21]:
tigercensuscodes.head()

          GEOID  PopulationValue    CENTLAT    CENTLON
0  200019526001           1791.0  37.873751 -95.203664
1  200019527001           1052.0  37.987188 -95.380907
2  200019527002            957.0  37.907415 -95.344626
3  200019528001           1179.0  37.942439 -95.420724
4  200019528002           1541.0  37.947521 -95.381379